### ISSUE TITLE
What differentiates this from slimv?

### ISSUE THREAD

**Issue by pebblexe** [l04m33/vlime#1]
Sorry, I haven't installed it yet because I haven't installed Vim 8 yet.

What features differentiate this from slimv?

**Comment by l04m33** [comment]
Slimv is really good at what it does, but it had some limitations.

When comparing to Slimv:

* Vlime doesn't have Python dependency while Slimv does. Vlime needs Quicklisp though.
* Vlime supports multiple SWANK connections, while Slimv doesn't.
* Vlime supports remote SWANK connections through SSH tunnels, while Slimv doesn't.
* Vlime uses the new channel & JSON APIs in Vim, which is faster than Slimv I believe. But there's no benchmark at the moment.
* Vlime has a rather different REPL implementation, which enables swank-presentations, that means you can copy & paste most of the values returned by the REPL, like you can in Emacs. Slimv cannot do this AFAIK.
* Vlime tries to be extendable. I think it's source code is better organized.

But Vlime has it's own limitations too:

* Vlime doesn't come with paredit mode, you'll need to install the paredit plugin, or other plugin of your choice, by yourself.
* Vlime is asynchronous. you can operate Vim when the server is processing a request. This may cause something weird if the request needs a long time to finish.
* While Vlime tries to be compatible with most major CL implementations, it's not been tested thoroughly on different platforms. Maybe you can help, by actually using it :)

There's a tutorial if you're interested: `:help vlime-tutor`

**Comment by pebblexe** [comment]
Thank you for that detailed response!
