### ISSUE TITLE
Plugin not loaded by Neovim/Vundle because of folder structure

### ISSUE THREAD

**Issue by daveyarwood** [l04m33/vlime#16]
I installed vlime in the usual way by adding `Plugin 'l04m33/vlime'` to my vimrc and running `:PluginInstall`. This cloned the repo in the correct place, but I noticed that the plugin was not being loaded after restarting Neovim and opening a lisp buffer.

I believe the plugin was not being loaded because the top level of the plugin folder `~/.vim/bundle/vlime` did not contain the expected folders `autoload`, `doc`, `ftplugin`, `syntax`, etc.

Instead, the project top-level structure of vlime is separated into two folders, `lisp` and `vim`.

I tried moving the contents of the `vim` folder out into the top-level, and after doing that and restarting Neovim, the basic functionality appears to be working. However, `<LocalLeader>rr` to have vlime start a server for me does not work because it's looking for `load-vlime.lisp` in the wrong directory, `~/.vim/bundle/lisp` instead of `~/.vim/bundle/vlime/lisp`.

EDIT: In case it helps anyone, I also ran `:VundleDocs` to update the helptags. This usually happens automatically when installing or updating plugins.

**Comment by daveyarwood** [comment]
Aha -- it turns out that there is a Vundle option for specifying the runtime path of the plugin.

Changing the line in my vimrc to this fixed it:

```viml
Plugin 'l04m33/vlime', {'rtp': 'vim/'}
```

**Comment by l04m33** [comment]
Glad you worked it out! Maybe I should make it clear in README or somewhere else.

**Comment by daveyarwood** [comment]
That's a good idea. Maybe you could provide examples of what to add to your vimrc, for different plugin managers? Something like this, maybe:

> [Vundle](https://github.com/VundleVim/Vundle.vim):
>
> ```viml
> Plugin 'l04m33/vlime', {'rtp': 'vim/'}
> ```
> [vim-plug](https://github.com/junegunn/vim-plug):
>
> ```viml
> Plug 'l04m33/vlime', {'rtp': 'vim/'}
> ```
>

I took a look at dein.vim and Pathogen, but I wasn't able to figure out how those plugin managers handle setting the runtime path.

EDIT: Looks like #10 has an example dein.vim plugin installation.
