### ISSUE TITLE
Allow the use of external terminals.

### ISSUE THREAD

**Issue by benrob0329** [l04m33/vlime#17]
Rather than trying to bring the terminal into vim (unless your Neovim) just use an external one. The current buffer style thing won't work in all circumstances (such as with a full TUI), and can leave a mess of buffers everywhere. Just sending the code to the already open terminal would fix many of these issues.

**Comment by l04m33** [comment]
I see that working with Vlime in a small terminal is irritating, because of all those split windows, but I'm not sure I grasped the solution you propose. Do you mean something like [vim-slime](https://github.com/jpalardy/vim-slime)?

Vlime's buffer management is indeed a bit chaotic at the moment. Some special buffers are still lying around after it's window was closed. Hopefully I can fix this soon.

**Comment by benrob0329** [comment]
I mean like, have the option of using the REPL from a real terminal emulator (be it URXVT, Gnome-Termninal, or GNU Screen if need be) by using the REPL that is already opened (or launched from Vim).

Example environment:
![1500602949](https://user-images.githubusercontent.com/19180682/28446366-5adf753e-6d98-11e7-9cab-35224fd88d6c.png)

**Comment by l04m33** [comment]
I'm sorry but I still don't get it 😅. If you just want to run the server in a separate terminal, Vlime can already do that. That's exactly what you showed in your screenshot.

To avoid confusion, can you describe your **desired workflow** by listing steps, and stress on the difference with Vlime's current workflow? For example, if I would like the REPL be launched in a separate terminal, I'd do this:

1. Start the server in a separate terminal by loading `start-vlime.lisp`.
2. Launch Vim in another terminal, and connect to the server, by pressing `\cc` or calling `vlime#plugin#ConnectREPL('127.0.0.1', 7002)`.
3. Send expressions to the REPL and read results from inside Vim.

**Comment by benrob0329** [comment]
Its 3 that I'd like to change, and have everything be done in the other terminal, rather than in a buffer.

**Comment by l04m33** [comment]
Ah, I see. Vlime kept everything in the buffers to make them available for further manipulation, e.g. copying and inspecting the results. I think a separate terminal can't provide decent UI for these tasks.

Currently the closest thing Vlime can do, is to use a vertical REPL window, by adding these to your `vimrc` (see `:help g:vlime_window_settings`):

```vim
let g:vlime_window_settings = {'repl': {'vertical': v:true, 'pos': 'botright'}}
```

If that's not what you want either, I think [vim-slime](https://github.com/jpalardy/vim-slime) may be a better tool for you.

**Comment by benrob0329** [comment]
Perhaps leaving the standard io in the terminal and having debugging etc in Vim would be a good mix. This would allow things that need editor integration to have them, but allow full TUIs to have a proper terminal.

**Comment by l04m33** [comment]
Vim recently introduced a full-featured embedded terminal, and Neovim already had this feature for some time, so I'm considering using the embedded terminal for launching the Vlime server. I think this will solve most of your problems. The Vim `:terminal` implementation is not quite stable at the moment though.

**Comment by l04m33** [comment]
I added a new option to instruct Vlime to use the built-in terminal emulators in both Vim and Neovim. Please refer to `:help g:vlime_cl_use_terminal`. If you're using Vim, this needs the recently-added `+terminal` feature.

**Comment by l04m33** [comment]
I'm closing this issue. Please feel free to re-open it for further discussion.
