### ISSUE TITLE
Help commands are not working (E149)

### ISSUE THREAD

**Issue by yonson2** [l04m33/vlime#18]
After a fresh installation of vlime on neovim 0.2.0-2 (on an up-to-date Arch machine) I can't open the help commands for vlime.
For example, typing `:help vlime` yields the following output:
```
E149: Sorry, no help for vlime
```
Vlime seems to be installed because after manually launching the sbcl server I can connect to it by typing `\cc` on nvim while editing a lisp file.

**Comment by l04m33** [comment]
Seems your help tags are outdated. Try running `:helptags ALL` in Neovim, and then try `:help vlime` again.

How did you install Vlime? If you used a plugin manager such as Vundle, the help tags should have been automatically updated.

**Comment by yonson2** [comment]
That did it, thank you. I did use a plugin manager ([plug](https://github.com/junegunn/vim-plug) and that hadn't happened before) I'll have it in mind for future occasions.

As far as I'm concerned, feel free to close this ticket now.
