### ISSUE TITLE
Compile/Send Toplevel Form

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#2]
I've been playing around with Vlime a bit and wondering about a few things.  I'll just brain dump them here into Github and maybe you can help.

I know about the `oe` and `se` commands to send the expression under the cursor, but 95% of the time what I *really* want is to send the entire toplevel form without having to manually move my cursor up to the top of the `(defun ...)` or whatever.

What's the proper way to do this with Vlime?  I can use `vim-sexp` to select the toplevel form, should I just do that and then call `VlimeCompileCurThing("selection")`?  Or is that function an internal implementation detail I shouldn't rely on.

In general it would be good to have some documentation about the public API of Vlime and what users should use if they want to script things.

**Comment by l04m33** [comment]
You are right. You can call `VlimeCompileCurThing("selection")` (or `VlimeSendCurThingToREPL("selection")`) to compile (or evaluate) the current selection. And I should probably at least provide a convenient API to return the top-level forms.

All functions starting with "Vlime" are intended for public usage, so are the functions exposed by the connection objects. I try not to break them. Hopefully I can add documentation for the APIs soon.
