### ISSUE TITLE
`flet`/`labels` indent incorrectly

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#21]
`flet` and `labels` currently indent like this:

    (flet ((foo (a)
                (1+ a)))
      (foo 10))

but the function bodies should indent only two spaces:

    (flet ((foo (a)
             (1+ a)))
      (foo 10))

This is an edge case that I had to hack around in my previous lisp indent script, so vlime probably needs to do something similar.

**Comment by l04m33** [comment]
Thanks. I'm aware of this problem, but couldn't get around to fix it yet. There are other glitches too, such as method clauses in DEFGENERIC, and condition clauses in HANDLER-CASE. I'd like to tackle them in a unified/generic-enough way if possible.

The indentation code in Vlime is rather simple, in that it only checks the operator for the innermost expression. To make it aware of its surroundings, a little refactoring may be necessary.

P.S.: Do you mind sharing your solution to this edge case?

**Comment by sjl** [comment]
> P.S.: Do you mind sharing your solution to this edge case?

Oh god.  Well, previously I was using a modified version of [this thing](https://github.com/ds26gte/scmindent), which maintains a stack of its current position as it reads forms.  I hacked in a special case there for to check if we're past the 2nd form in the list and the thing 2 levels up the stack was a `flet` or `labels` and use the proper indentation if so.  It's awful: https://bitbucket.org/sjl/dotfiles/commits/ab4a7458c22c748a0b1a4eb1b0ad60e39e101f6f

**Comment by l04m33** [comment]
Thank you! Actually the indent code in Vlime was implemented by following the indent rules summarized by the author of `scmindent` (https://ds26gte.github.io/scmindent/index.html), so your patch may be quite relevant.

And it seems to me that the only way to fix this in Vlime is to parse more surrounding Lisp code.

**Comment by l04m33** [comment]
As of commit a1ee9f7, FLET/LABELS/MACROLET should indent properly. Please try it out.

**Comment by sjl** [comment]
Looks like it works now, thanks!
