### ISSUE TITLE
Inspector `p` doesn't get buffer mapped if `p` is globally mapped

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#3]
I use miniyank to handle yanking and pasting in most buffers, and have something like `nnoremap p ...` in my `vimrc`.  Vlime's inspector window doesn't map its `p` buffer-local mapping unless I remove this global one.  Vlime seems to be trying to be "helpful" and not mapping keys that are already mapped, even for windows like the inspector and debugger that aren't editable.

What's the right way for me to work around this?  Unmap my keys, run `map foo` to see what internal Vlime function it's calling, remap my keys, and remap the Vlime key in an autocommand?  Is there an easier way?

**Comment by l04m33** [comment]
Yes this is expected. Vlime will not map any keys that are already mapped. I try not to assume any key usage.

All Vlime special buffers have file types, you can use the FileType autocmd to forcibly map the key:

```VimL
augroup LocalVlimeKeys
    autocmd FileType vlime_inspector nnoremap <silent> <buffer> p :call vlime#ui#inspector#InspectorPop()<cr>
augroup end
```

Or is there a better effortless way to handle conflicting keys?

**Comment by sjl** [comment]
This way is fine, but it would be good if the documentation could list the function for each key it maps, so I don't need to do the unmap/check/remap dance for all of them.

**Comment by l04m33** [comment]
> but it would be good if the documentation could list the function for each key it maps

True, but I thought this is a bit too verbose, and hard to maintain. Maybe I can come up with a unified naming scheme for the mapped functions, and let the users derive the names.

Or should I provide a override-all-mappings configuration option?

**Comment by l04m33** [comment]
Another option may be that, Vlime throws all skipped keys (and what they should be mapped to) in a global variable, so that you can inspect them easily, just like how `v:errors` and `v:errmsg` work.

**Comment by l04m33** [comment]
As of b547007, one can simply say `let g:vlime_force_default_keys = v:true` to have all the default mappings.
