### ISSUE TITLE
vlime#Connect: failed to open channel

### ISSUE THREAD

**Issue by rberaldo** [l04m33/vlime#33]
Hi, I'm using neovim v0.2.2 and SBCL 1.3.1.debian. I start the server as in the readme and open a lisp file in neovim. Then I run the `\cc` command but I get the error `vlime#Connect: failed to open channel`. I don't seem to have a firewall running or anything like that. Searching online for the error message was unfruitful.

Has anybody ever seen this bug?

**Comment by rberaldo** [comment]
Had I read the [dependency list](https://github.com/l04m33/vlime#dependencies) I'd have saved myself from having written the bug above. I didn't have `ncat` installed. To anyone who might have overlooked the list of dependencies, install `nmap`.

**Comment by cbcoutinho** [comment]
For anyone interested, on OpenSUSE `ncat` is separate package from `nmap`
