### ISSUE TITLE
Failure to enter debugger

### ISSUE THREAD

**Issue by jurov** [l04m33/vlime#37]
When evaluating (for example using \ss)

> (concatenate 'string '("blabla"))

fails to open debugger for the TYPE-ERROR, it does nothing and whole vlime server is stuck, must be restarted. Other errors are handled fine.

SBCL: 1.4.9 on Linux x64
Vlime: master
NeoVIM: v0.3.3

**Comment by jurov** [comment]
Updated sbcl to 1.4.15 and all quicklisp dists, no change.

**Comment by phmarek** [comment]
Works fine for me - but with much newer software versions.

Can you still reproduce?

**Comment by jurov** [comment]
Can't reproduce with newest version.
