### ISSUE TITLE
Jump to definition without opening new tab

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#4]
When I run `xd` to jump to a definition Vlime will focus the buffer's window if one currently exists, otherwise it opens a new tab page.  I never use tabs in Vim and would ideally like it to open in the buffer I just left like Vim's `<ctrl-]>`, e.g.:

1. I'm in a window and have my cursor on something.
2. I press `<localleader>xd`.
3. It opens the xref window thing.
4. I press `<cr>` to pick one.
5. It opens the location in the same window from step 1.

Ideally I'd also like two extra things:

* Close the xref window after I jump, to reduce clutter.
* If there's only one result, don't bother opening the xref window and making me press return, just jump to that one result.

Is there some way I can implement this stuff myself, or would it require changing Vlime?

**Comment by l04m33** [comment]
The behaviors you proposed are indeed more intuitive. I think it's possible to implement these features in your vimrc, but it would be quite messy.

I'll see what I can do. And I should probably make this configurable, because I prefer tabs myself :)

**Comment by l04m33** [comment]
As of 0bc01d9, when jumping to source locations, Vlime will use existing windows by default. The xref window will still appear even though there's only one match, to allow the user to choose a preferred way of opening the source file (see `:help vlime-mappings-xref`).
