### ISSUE TITLE
Closing the preview window

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#5]
Is there a way to close the Vlime preview window without manually moving over to it, `:q`ing, and manually moving back to where I was?  Doing this dance every time I want to view a docstring is really painful.

If I had a huge monitor I could just leave all various Vlime buffers open in dedicated windows all the time, but I use a laptop need to keep things uncluttered if I want to be able to get anything done.

**Comment by l04m33** [comment]
Yes, I can add a default mapping for this, and maybe other windows that doesn't normally have focus, such as the arglist window.

You can try this in your vimrc for a quick patch:

```VimL
function! RcVlimeClosePreview()
    let winnr = bufwinnr(vlime#ui#PreviewBufName())
    if winnr <= 0
        return
    endif

    execute winnr . 'wincmd c'
endfunction

augroup LocalVlimeKeys
    autocmd!
    autocmd FileType lisp nnoremap <silent> <buffer> <LocalLeader>wp :call RcVlimeClosePreview()<cr>
augroup end
```
