### ISSUE TITLE
Input buffer: Attempt to delete a buffer that is in use

### ISSUE THREAD

**Issue by mwgkgk** [l04m33/vlime#51]
When submitting the input buffer with `Return`, following error happens:
```
Error detected while processing BufWinLeave Autocommands for "<buffer=5>":
E937: Attempt to delete a buffer that is in use: vlime | input | Vlime Connection 1 | Input string:
```
The value does go through however.

Tested with following .vimrc with an empty .vim/ directory besides plug.vim:

```vim
set nocompatible

call plug#begin('~/.vim/plugs/')

Plug 'vlime/vlime'

call plug#end()
```
Launching a repl with `<LocalLeader>rr`, and sending e.g. this:
```lisp
(read-line *query-io*)
```
;;

More data:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
Included patches: 1-148
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl/dyn
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl/dyn          +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
```
```
SBCL 2.0.0
```
```
~/.vim/plugs/vlime git log --oneline -n 1
64e6220 (grafted, HEAD -> master, origin/master, origin/HEAD) Merge pull request #50 from vlime/fix/vim-tests
```

**Comment by rknegjens** [comment]
I have the same issue.

I'm using pathogen to load vlime.

Same vim, also on archlinux:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)
Included patches: 1-148
Compiled by Arch Linux
```
```
SBCL 2.0.1
```
```
ceee9fe (HEAD, origin/master, origin/HEAD, master) Fix *json-cache* to work on other implementations than SBCL.
```

**Comment by mwgkgk** [comment]
Developments:

-  Issue is not reproducible in NeoVim.

-  Here's where it's triggered from:

In `autoload/vlime/ui/input.vim`,
In `function vlime#ui#input#FromBuffer`:

```vim
augroup VlimeInputBufferLeaveAu
    autocmd!
    execute 'autocmd BufWinLeave <buffer> bunload!' buf
augroup end
```
`:bunload!` discards changes, closes any windows for this buffer, and frees the memory allocated for it. `BufWinLeave` is triggered before a buffer is removed from a window, not when it's still visible in another window, also triggered when exiting.

The Input buffer has `setbufvar(buf, '&buflisted', 0)`, which means it doesn't show up in the operations involving the buffer list. To show all buffers the including unlisted ones, we can use `:buffers!`. Which, reasonably enough, the Input buffer shows up in, regardless of whether the above autocommand is present.

So the idea behind this line is to unload the memory allocated for whatever content we've put into the buffer, before we close it without removing from the (hidden-) buffer list. If we wanted to also remove it from the (hidden-) buffer list, we would use `bdelete!` instead of `bunload!`. Reasonably enough (since the former includes the latter), either command causes the same error.

Moving the autocommand up the [autocommand stack](https://vi.stackexchange.com/a/4495) to `BufLeave` solves the error, however this autocommand is triggered upon switching windows as well, which means we can destroy the buffer before we submit, which is undesirable. The autocommands down the stack that we could attach to, are (`BufUnload`, `BufDelete`, ...) are not exactly what we need either, and also happen to trigger the error (even if the construct itself now makes little sense). We are attempting to delete a buffer that is in use. The `E937` help pertains to a group of autocommand-related errors and does not clear up this issue.

- _**We run `bdelete!` when we submit the Input buffer anyways:**_

As defined in the same `function vlime#ui#input#FromBuffer` we were discussing previously:

```vim
nnoremap <buffer> <silent> <cr> :call vlime#ui#input#FromBufferComplete()<cr>
```

`vlime#ui#input#FromBufferComplete` calls the clean up by itself:

```vim
execute 'bdelete!' input_buf
```

Which means the following: the buffer IS being run `bdelete!` on, (which itself triggers `bunload!`), when it's submitted with the `<CR>` key.

So the only case where the problematic autocommand is relevant, is when we forcibly close the buffer without submitting it first. Which is problematic in itself, because further Lisp calls that would otherwise trigger the buffer, are put on hold until we find the buffer number in the `buffers!` list (because it's otherwise hidden from buffer-related commands), and then switch to it by it's number, e.g. `:b 5`. After that the situation resolves itself and the Input buffer will appear as many times as it was needed for the queued calls.

An alternative to deleting the autocommand outright, is to place it in an optional nvim block:

```vim
if has('nvim')
    augroup VlimeInputBufferLeaveAu
        autocmd!
        execute 'autocmd BufWinLeave <buffer> bunload!' buf
    augroup end
endif
```

**Comment by mwgkgk** [comment]
Another way of addressing this can be seen in pull request  #48, which is handling the unload in a try block:
```vim
function! s:BufUnload(buf) abort
  try
    execute 'bunload!' a:buf
  catch /^Vim\%((\a\+)\)\=:E937:/
    return
  endtry
endfunction
```
```vim
augroup VlimeInputBufferLeaveAu
    autocmd!
    execute 'autocmd BufWinLeave <buffer> call s:BufUnload(' buf ')'
augroup end
```
Which seems more idiomatic than introducing an unwarranted `nvim` branch like above. I humbly call for @fukamachi to merge it!

**Comment by mwgkgk** [comment]
Deleting the problematic block entirely also seems like a valid option, as the functionality it brings is highly questionable, as discussed in above https://github.com/vlime/vlime/issues/51#issuecomment-614379776.
