### ISSUE TITLE
One-off calls

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#6]
Often I want to look up documentation, jump to definition, etc of something that's not currently written in my Lisp file.  Is there a way I can look up the definition of (or jump to, etc etc) an arbitrary string without typing it into my lisp buffer, running the key mapping, then undoing the typing?

Ideally I'd be able to make a mapping like `nnoremap <localleader>dd? :call VlimeDocumentationForSymbol(input("Symbol Name? "))<cr>`.  I looked in the Vlime source and it seems like `VlimeDocumentationForSymbol()` just expects one of the two magic strings `"atom"` or `"operator"`... any change we could get a separate function that could take the symbol name itself?

**Comment by l04m33** [comment]
Good point. I can certainly add mappings for these one-off calls, but maybe re-arrange the code a bit first.

In the mean time, you can use the lower-level APIs to achieve what you want. Try this in your vimrc:

```VimL
function! RcVlimeDoc(sym)
    let conn = VlimeGetConnection()
    if type(conn) == type(v:null)
        return
    endif
    call conn.DocumentationSymbol(a:sym,
                \ {c, r -> vlime#ui#ShowPreview(c, r, v:false)})
endfunction

augroup LocalVlimeKeys                                                                                                                       
    autocmd!
    autocmd FileType lisp nnoremap <silent> <buffer> <LocalLeader>dd? :call RcVlimeDoc(input('Symbol name? '))<cr>
augroup end
```

Unfortunately there isn't any documentation about these low level APIs, even though they can be quite useful. You have to read the code (`vim/autoload/vlime.vim`). I should probably improve the docs and add sections about these APIs.

**Comment by l04m33** [comment]
As of 7282f1f, there are default mappings for some one-off operations, and most of the top-level API functions are updated to have an one-off input mode.

**Comment by sjl** [comment]
This looks perfect, thanks!
