### ISSUE TITLE
Request consideration to "rename" the project

### ISSUE THREAD

**Issue by ghost** [l04m33/vlime#70]
"vlime" seems to be a carry-over from SLIME, probably because "vlime" (currently) depends on SLIME for SWANK.
That might not hold true in the future and hence I request that you consider renaming the project to something more Vim-like.
My suggestion is "vicle" for "Vim Common Lisp Environment", rhymes with pickle.  ;-)

**Comment by phmarek** [comment]
No, `vlime` does not depend on `SLIME`, but only on `swank`.

Due to the number of references to `vlime` I'd rather stick with the current name.
