### ISSUE TITLE
Fix this bug introduced by upstream: thread waiting

### ISSUE THREAD

**Issue by equwal** [l04m33/vlime#80]
Upstream declined my pull:

https://github.com/slime/slime/pull/770

can it be fixed on vlime's side?

**Comment by phmarek** [comment]
It *is* fixed - at least on the JSON branch, see ac21427d85234b39ae301a0723bf9ab1126157ef.

I cherry-picked that as cfaac6ccb379f9f85bfb2ef17ca6369dfadf2be6 as well, is that enough?

**Comment by equwal** [comment]
I wasn't able to get the json branch working.

I didn't cherry pick the commit, I reverted it though? I just did a `git bisect` until I found it, then reverted and patched. I suppose it is better to actually fix the problem on the client end so I'll close it.
