### ISSUE TITLE
Yanking more things

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#9]
I've been using Vlime for a few days now and one of the things I find myself constantly wanting to do is to yank an object from the inspector or debugger so I can poke at it further.  I know I can use `\y` in the REPL to yank things there, but is there a way to do the same from the inspector or debugger?

**Comment by l04m33** [comment]
Hmm, what object do you need from the debugger? Can you give an example? AFAIK the Swank server doesn't have an API for extracting objects from the debugger, so I don't think it's possible to yank things from there. But there's chance you can get what you want from somewhere else, or from other APIs. We may then add shortcuts for them.

As for the inspector, there's the `SWANK:INSPECTOR-NTH-PART` function, which returns the specified object. I think we can make use of it. But this function is a bit inconsistent, in that updating the inspector may change the value it returns. I'm not yet sure how to handle this inconsistency.

**Comment by l04m33** [comment]
Well, I found this in the Slime manual regarding copying values in the inspector:

> M-RET
> M-x slime-inspector-copy-down
>
>     Store the value under point in the variable ‘*’. This can then be used to access the object in the REPL.

For Vlime, I'd say we just evaluate `(swank:inspector-nth-part ...)` from the inspector, and let the result show up in the REPL buffer, so that one can yank that value with the good old `\y` command. I can add a key mapping for this.

**Comment by sjl** [comment]
> Hmm, what object do you need from the debugger?

Mostly the arguments for a particular frame, e.g. the `0` here:

![screenshot](https://i.imgur.com/D0NiGMd.png)

**Comment by l04m33** [comment]
I see. There's a not-so-straightforward way to access frame local variables. In the case of your example:

1. Press `e` on frame 0;
2. In the input buffer, write `(setf cl-user::* sb-debug::arg-0)`, and press `<CR>` in normal mode;
3. The value you need would be accessible via the `*` variable in the REPL.

I think I can make a shortcut for these steps.
