### ISSUE TITLE
Quote

### ISSUE THREAD

**Issue by bigcattus** [l04m33/vlime#93]
A question, 

why does 

CL-USER(3): '("eat" "carrot")

("eat" "carrot")

work at the sbcl prompt, but give me an error

Execution of a form compiled with errors.                     
Form:                                                                                          
  ("eat" "carrot")                                                                             
Compile-time error:                                   
  illegal function call                                                                        
   [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]    

in vlime (I am using it with a fairly recent neovim).

Thank you.

**Comment by phmarek** [comment]
You don't say how you evaluate the form, but the hotkeys look at the S-expression delimited by parenthesis and ignore the quote in front.

You could try
```lisp
(identity '("eat" "carrot"))
```

Also, perhaps selecting the form *and* the quote (eg. via `va(oh`) and evaluating that (https://github.com/vlime/vlime/blob/master/vim/doc/vlime.txt#L645) might work as well.

**Comment by bigcattus** [comment]
Indeed I was using a hotkey (\ss) to evaluate.  Thank you for the explanation.
