### ISSUE TITLE
Syntax highlighting is lost on buffers that haven't yet been viewed when starting server

### ISSUE THREAD

**Issue by nytpu** [l04m33/vlime#96]
If you open Neovim with multiple Lisp files (whether from a bunch of arguments, loading a saved session, whatever), then if you launch a server or connect to an existing server, syntax highlighting is lost on all files that haven't been viewed yet.  Other filetype-specific functions like autocompletion and Vlime's hotkeys still work.  Things relating to color but not necessarily syntax highlighting like rainbow parentheses are also affected.

The only way to restore syntax highlighting is to manually run `set filetype=lisp` in all the affected buffers, even though the filetype was already correctly displayed as `lisp`.  `:bufdo set filetype=lisp` either before or after starting the server does not fix it either, each buffer must be individually visited and have the command run manually.  `syntax sync fromstart` does not help.

The files must have been actually displayed on the screen for a non-negligible period of time to not be affected, not even something like `:bufdo e` prior to connecting prevents it.

Reproducible using a stock Neovim v0.10.2 install (and empirically previous versions), minimally with this vimrc:
```vim
source ~/.local/share/nvim/site/autoload/plug.vim

call plug#begin()
Plug 'vlime/vlime', {'rtp': 'vim/'}
call plug#end()
```
And then invoked like this:
`nvim --clean -u /tmp/init.vim <multiple source files>`

Do not switch away from the first file, then start a new server or connect to an already running server using the hotkeys.  The first file will be highlighted like normal, but then toggling through the other files with `:n`, none will have syntax highlighting.  If you partially go through the opened files, the ones that were viewed prior to starting the server will be unaffected.

[Demonstration](https://github.com/user-attachments/assets/c6e5898e-fa45-4ef3-9601-d6848a014233)

**Comment by phmarek** [comment]
Yeah, right.

Any ideas? Would you try with `nvim --cmd "set verbose=255 verbosefile=/tmp/trace.log <source files>"` and see what's different for the others?

**Comment by nytpu** [comment]
I've trawled through the logs but still haven't been able to find the root cause.  I've observed it in a few other situations unrelated to Lisp though so it's unlikely it's caused by anything vlime is doing
